"""Shared deterministic skill governance workflow built on harness records."""

from __future__ import annotations

import re
import tempfile
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from agent.harness.models import BudgetSummary, DecisionRecord, HarnessTask, TaskBrief
from agent.harness.profiles import get_squad_profile
from agent.iteration_observation import OBSERVING_STATUS, observation_outcome
from agent.iteration_review import (
    HEADING_RE,
    MANAGED_ADJUSTMENTS_HEADING,
    extract_section,
    review_proposal,
    split_frontmatter,
    strip_managed_adjustments,
)
from agent.skill_feedback import SkillFeedbackSummary, summarise_skill_feedback
from skills.aggregation import aggregate_version_evidence
from skills.governance import text_digest
from skills.loader import parse_skill

_VERSION_LINE_RE = re.compile(r"(?m)^version:\s*.*$")
_SEMVER_RE = re.compile(r"^(\d+)\.(\d+)\.(\d+)(?:[-+].*)?$")


@dataclass
class UpdateResult:
    path: str
    strategy: str
    has_changes: bool
    old_content: str
    new_content: str


@dataclass
class IterationDecisionPacket:
    skill_name: str
    skill_path: str
    skill_origin: str
    skill_version: str = ""
    update_section: str = "## Reference Data"
    current_content: str = ""
    metrics_summary: dict[str, Any] = field(default_factory=dict)
    outcome_summary: dict[str, Any] | None = None
    regression_summary: dict[str, Any] = field(default_factory=dict)
    exemplar_slice: list[dict[str, Any]] = field(default_factory=list)
    executions: list[dict[str, Any]] = field(default_factory=list)
    execution_contract: dict[str, Any] | None = None
    execution_evaluations: list[dict[str, Any]] = field(default_factory=list)
    typed_evaluation_results: list[dict[str, Any]] = field(default_factory=list)
    governance_aggregate: dict[str, Any] = field(default_factory=dict)
    outcome_contract: dict[str, Any] | None = None
    outcome_summaries: list[dict[str, Any]] = field(default_factory=list)
    feedback: SkillFeedbackSummary | None = None
    lifecycle_history: list[dict[str, Any]] = field(default_factory=list)
    experiment_history: list[dict[str, Any]] = field(default_factory=list)
    # Full proposed SKILL.md generated by an LLM outside the harness (optional).
    llm_rewrite_proposal: str = ""
    surface: str = "run"
    conversation_id: str = ""
    task_kind: str = "skill_iteration"


@dataclass
class IterationDecision:
    decision: str
    skill_status: str
    update: UpdateResult
    task: HarnessTask


def replace_section(content: str, heading: str, new_section: str) -> str:
    """Replace a markdown section by heading, appending if missing."""
    target = heading.lstrip("#").strip()
    lines = content.split("\n")
    start_idx: int | None = None
    start_level: int | None = None

    for idx, line in enumerate(lines):
        match = HEADING_RE.match(line)
        if not match:
            continue
        level = len(match.group(1))
        title = match.group(2).strip()
        if start_idx is None and title == target:
            start_idx = idx
            start_level = level
        elif start_idx is not None and level <= (start_level or 0):
            replaced = lines[:start_idx] + new_section.rstrip().split("\n") + lines[idx:]
            return "\n".join(replaced).rstrip() + "\n"

    if start_idx is not None:
        replaced = lines[:start_idx] + new_section.rstrip().split("\n")
        return "\n".join(replaced).rstrip() + "\n"

    suffix = "" if not content.strip() else "\n\n"
    return content.rstrip() + suffix + new_section.rstrip() + "\n"


def _set_frontmatter_version(content: str, version: str) -> str:
    prefix, body = split_frontmatter(content)
    if not prefix:
        raise ValueError("Automatic Skill candidates require YAML frontmatter")
    if _VERSION_LINE_RE.search(prefix):
        prefix = _VERSION_LINE_RE.sub(f"version: {version}", prefix, count=1)
    else:
        lines = prefix.rstrip("\n").splitlines()
        lines.insert(len(lines) - 1, f"version: {version}")
        prefix = "\n".join(lines) + "\n"
    return prefix + body.lstrip("\n")


def _next_runtime_version(version: str) -> str:
    match = _SEMVER_RE.match(version or "")
    if match:
        major, minor, patch = (int(value) for value in match.groups())
        return f"{major}.{minor}.{patch + 1}"
    timestamp = datetime.now(timezone.utc).strftime("%Y%m%d%H%M%S%f")
    return f"{version or 'unversioned'}-iter-{timestamp}"


def _atomic_write_skill(path: Path, content: str, *, expected_name: str) -> None:
    """Validate and atomically replace one active SKILL.md."""
    if not path.is_file():
        raise ValueError("Automatic Skill updates require an existing skill file")
    mode = path.stat().st_mode if path.exists() else None
    temporary: Path | None = None
    try:
        with tempfile.NamedTemporaryFile(
            "w",
            encoding="utf-8",
            dir=path.parent,
            delete=False,
            prefix=f".{path.name}.",
            suffix=".tmp",
        ) as handle:
            handle.write(content)
            temporary = Path(handle.name)
        if split_frontmatter(content)[0]:
            parsed = parse_skill(temporary)
            if parsed.name != expected_name:
                raise ValueError(
                    f"Automatic Skill update changed name: {parsed.name} != {expected_name}"
                )
        if mode is not None:
            temporary.chmod(mode)
        temporary.replace(path)
        temporary = None
    finally:
        if temporary is not None:
            temporary.unlink(missing_ok=True)


def _build_rewritten_instructions(
    instructions_body: str,
    *,
    outcome_contract: dict[str, Any],
    outcome_summary: dict[str, Any] | None,
    regression_summary: dict[str, Any],
    exemplar_slice: list[dict[str, Any]],
    feedback: SkillFeedbackSummary,
    governance_aggregate: dict[str, Any],
) -> str:
    base = strip_managed_adjustments(instructions_body).rstrip()
    primary_kpi = outcome_contract.get("primary_kpi") or "the primary KPI"
    lines = ["## Instructions", ""]
    if base:
        lines.append(base)
        lines.append("")

    lines.append(MANAGED_ADJUSTMENTS_HEADING)
    lines.append("")
    if outcome_summary:
        current_value = outcome_summary.get("current_value")
        baseline_value = outcome_summary.get("baseline_value")
        delta = outcome_summary.get("delta")
        if current_value is not None and baseline_value is not None and delta is not None:
            lines.append(
                f"- Optimize for `{primary_kpi}` using the latest window evidence: "
                f"current={current_value:.3f}, baseline={baseline_value:.3f}, delta={delta:.3f}."
            )
    if regression_summary.get("rewrite_candidate"):
        lines.append(
            f"- Prioritize changes that improve `{primary_kpi}` in the weakest current segment."
        )
    for pattern in regression_summary.get("legacy_patterns", [])[:3]:
        lines.append(f"- Reinforce this observed pattern: {pattern}.")
    for segment in (outcome_summary or {}).get("segment_breakdown", [])[:2]:
        label = ", ".join(f"{k}={v}" for k, v in segment.get("segment", {}).items())
        lines.append(
            f"- Address the regression in segment `{label or 'default'}` "
            f"(value={segment['value']:.3f}, samples={segment['sample_count']})."
        )
    for exemplar in exemplar_slice[:2]:
        label = exemplar.get("exemplar") or exemplar.get("entity_id") or "example"
        value = exemplar.get(primary_kpi)
        if value is not None:
            lines.append(f"- Learn from exemplar `{label}` ({primary_kpi}={value:.3f}).")
    for failure, count in (governance_aggregate.get("actionable_failure_modes") or {}).items():
        lines.append(
            f"- Explicitly prevent observed failure mode `{failure}` "
            f"({count} attributed execution(s))."
        )
    hard_gate_names = sorted(
        {
            item["name"]
            for item in governance_aggregate.get("hard_gate_failures", [])
            if item.get("attribution_grade") in {"direct", "controlled"}
        }
    )
    for failure in hard_gate_names:
        lines.append(f"- Treat hard-gate failure `{failure}` as non-negotiable.")
    lines.append(
        "- Keep the manual guidance above intact; treat these adjustments as evidence-backed overrides only."
    )
    if feedback.average_score is not None:
        lines.append(
            f"- Recent execution evaluator average is {feedback.average_score:.2f}; do not trade execution quality for KPI gains."
        )
    return "\n".join(lines)


def build_decision_packet(
    memory,
    *,
    skill,
    current: str,
    feedback: SkillFeedbackSummary | None = None,
    result=None,
    surface: str = "run",
    conversation_id: str = "",
    task_kind: str = "skill_iteration",
) -> IterationDecisionPacket:
    """Build the unified evidence packet used by run, serve, and web feedback."""

    state = memory.get_skill_state(skill.name)
    emerged = memory.get_emerged_skill(skill.name)
    origin = state["origin"] if state else ("emerged" if emerged else "base")
    executions = memory.get_skill_executions(skill.name, limit=20)
    execution_contract_row = memory.get_skill_evaluation_contract(skill.name)
    execution_contract = execution_contract_row.get("contract") if execution_contract_row else None
    execution_evaluations = memory.list_skill_evaluations(skill.name, limit=20)
    all_typed_results = memory.list_evaluation_results(skill_name=skill.name, limit=100)
    hidden_execution_ids = {
        int(item["execution_id"])
        for item in all_typed_results
        if str((item.get("metadata") or {}).get("split") or "") in {"holdout", "security_holdout"}
    }
    typed_evaluation_results = [
        item for item in all_typed_results if int(item["execution_id"]) not in hidden_execution_ids
    ]
    executions = [
        item for item in executions if int(item.get("id") or 0) not in hidden_execution_ids
    ]
    governance_aggregate = aggregate_version_evidence(
        typed_evaluation_results,
        skill_name=skill.name,
        skill_version=skill.version,
    ).to_dict()
    outcome_summaries = memory.list_outcome_window_summaries(skill.name, limit=20)

    outcome_summary = getattr(result, "outcome_summary", None) if result is not None else None
    regression_summary = dict(getattr(result, "regression_summary", {}) or {})
    exemplar_slice = list(getattr(result, "exemplar_slice", []) or [])
    metrics_summary = dict(getattr(result, "raw_stats", {}) or {})
    if result is not None and not exemplar_slice:
        top_performers = list(getattr(result, "top_performers", []) or [])
        exemplar_slice = [
            {
                "entity_id": getattr(item, "title", ""),
                "exemplar": getattr(item, "title", ""),
                **dict(getattr(item, "metrics", {}) or {}),
            }
            for item in top_performers
        ]
        if top_performers:
            metrics_summary.setdefault(
                "top_titles",
                [getattr(item, "title", "") for item in top_performers],
            )
    if result is not None and "legacy_patterns" not in regression_summary:
        patterns = list(getattr(result, "patterns", []) or [])
        if patterns:
            regression_summary["legacy_patterns"] = patterns

    return IterationDecisionPacket(
        skill_name=skill.name,
        skill_path=str(skill.path),
        skill_origin=origin,
        skill_version=skill.version,
        update_section=skill.update_section,
        current_content=current,
        metrics_summary=metrics_summary,
        outcome_summary=(
            {
                "window": outcome_summary.window,
                "sample_count": outcome_summary.sample_count,
                "baseline_value": outcome_summary.baseline_value,
                "current_value": outcome_summary.current_value,
                "delta": outcome_summary.delta,
                "confidence": outcome_summary.confidence,
                "segment_breakdown": outcome_summary.segment_breakdown,
                "policy_state": outcome_summary.policy_state,
            }
            if outcome_summary is not None
            else None
        ),
        regression_summary=regression_summary,
        exemplar_slice=exemplar_slice,
        executions=executions,
        execution_contract=(
            skill.execution_contract.to_dict() if skill.execution_contract else execution_contract
        ),
        execution_evaluations=execution_evaluations,
        typed_evaluation_results=typed_evaluation_results,
        governance_aggregate=governance_aggregate,
        outcome_contract=skill.outcome_contract.to_dict() if skill.outcome_contract else None,
        outcome_summaries=outcome_summaries,
        feedback=feedback or summarise_skill_feedback(executions),
        lifecycle_history=memory.list_skill_lifecycle_events(skill.name, limit=20),
        experiment_history=memory.list_skill_experiments(skill.name, limit=20),
        surface=surface,
        conversation_id=conversation_id,
        task_kind=task_kind,
    )


class IterationHarness:
    """Deterministic workflow for keep/rewrite/rollback/disable decisions."""

    def __init__(self, memory) -> None:
        self.memory = memory

    def run(self, *, packet: IterationDecisionPacket) -> IterationDecision:
        task = HarnessTask(
            id=f"iter-{packet.skill_name}-{datetime.now(timezone.utc).strftime('%Y%m%d%H%M%S%f')}",
            conversation_id=packet.conversation_id,
            surface=packet.surface,
            squad=get_squad_profile("iteration"),
            brief=TaskBrief(
                user_input=f"Govern skill {packet.skill_name}",
                conversation_id=packet.conversation_id,
                selected_skills=[packet.skill_name],
            ),
            budget_summary=BudgetSummary(max_rounds=1),
        )
        self.memory.create_harness_task(
            task_id=task.id,
            conversation_id=packet.conversation_id,
            surface=packet.surface,
            squad_profile="iteration",
            status="running",
            task_kind=packet.task_kind,
            user_input=packet.skill_name,
            selected_skills=[packet.skill_name],
            role_roster=task.squad.roles,
            budget=task.budget_summary.to_dict(),
        )

        evidence = self._evidence_payload(packet)
        evidence_step = self.memory.record_harness_step(
            task.id,
            phase="collect",
            role="evidence_collector",
            status="completed",
            summary=self._summarise(f"Collected evidence for {packet.skill_name}"),
            tool_trace=[],
            budget=task.budget_summary.to_dict(),
        )
        self.memory.record_harness_artifact(
            task.id,
            step_id=evidence_step,
            phase="collect",
            role="evidence_collector",
            kind="evidence",
            summary=self._summarise(str(evidence)),
            content=str(evidence),
            accepted=True,
            meta=evidence,
        )

        decision, proposed_content, proposal_meta = self._propose(packet)
        proposer_step = self.memory.record_harness_step(
            task.id,
            phase="propose",
            role="rewrite_proposer",
            status="completed",
            summary=self._summarise(f"Proposal decision: {decision}"),
            tool_trace=[],
            budget=task.budget_summary.to_dict(),
        )
        self.memory.record_harness_artifact(
            task.id,
            step_id=proposer_step,
            phase="propose",
            role="rewrite_proposer",
            kind="proposal",
            summary=self._summarise(proposed_content or decision),
            content=proposed_content or decision,
            accepted=decision == "keep",
            meta={"decision": decision, **proposal_meta},
        )

        review = review_proposal(decision, packet, proposed_content)
        review_summary = (
            "Approved proposal"
            if review.approved
            else "Rejected proposal: " + "; ".join(review.reasons)
        )
        reviewer_step = self.memory.record_harness_step(
            task.id,
            phase="review",
            role="safety_reviewer",
            status="completed",
            summary=self._summarise(review_summary),
            tool_trace=[],
            budget=task.budget_summary.to_dict(),
        )
        self.memory.record_harness_artifact(
            task.id,
            step_id=reviewer_step,
            phase="review",
            role="safety_reviewer",
            kind="review",
            summary=self._summarise(
                "approved" if review.approved else "rejected: " + "; ".join(review.reasons)
            ),
            content="approved" if review.approved else "rejected",
            accepted=review.approved,
            meta={"decision": decision, "checks": review.checks, "reasons": review.reasons},
        )
        if decision in {"rewrite", "rollback", "refresh"} and not review.approved:
            decision = "keep"
            proposed_content = ""

        arbiter_step = self.memory.record_harness_step(
            task.id,
            phase="decide",
            role="lifecycle_arbiter",
            status="completed",
            summary=self._summarise(f"Lifecycle decision: {decision}"),
            tool_trace=[],
            budget=task.budget_summary.to_dict(),
        )

        update, skill_status = self._apply_decision(
            packet=packet,
            decision=decision,
            proposed_content=proposed_content,
            harness_task_id=task.id,
            proposal_meta=proposal_meta,
        )
        task.decision = DecisionRecord(decision=decision, rationale=f"Decision={decision}")
        task.status = "completed"
        task.final_output = decision
        task.convergence_summary = {"decision": decision, "skill_status": skill_status}
        self.memory.record_harness_artifact(
            task.id,
            step_id=arbiter_step,
            phase="decide",
            role="lifecycle_arbiter",
            kind="decision",
            summary=self._summarise(decision),
            content=decision,
            accepted=True,
            meta={
                "path": update.path,
                "has_changes": update.has_changes,
                "skill_status": skill_status,
            },
        )
        self.memory.update_harness_task(
            task.id,
            status="completed",
            summary=self._summarise(decision),
            convergence=task.convergence_summary,
            final_output=decision,
            budget=task.budget_summary.to_dict(),
        )
        return IterationDecision(
            decision=decision,
            skill_status=skill_status,
            update=update,
            task=task,
        )

    def _propose(self, packet: IterationDecisionPacket) -> tuple[str, str, dict[str, Any]]:
        feedback = packet.feedback or summarise_skill_feedback(packet.executions)
        latest_rewrite = self._latest_rewrite_event(packet.lifecycle_history)
        reference_content = self._build_reference_content(packet)
        execution_decision = self._execution_contract_decision(packet)
        outcome_policy = (packet.outcome_summary or {}).get("policy_state", {})
        open_candidates = (
            self.memory.list_skill_experiments(packet.skill_name, status="candidate", limit=1)
            if packet.surface == "eval"
            else []
        )
        if open_candidates:
            pending = open_candidates[0]
            if (
                execution_decision == "disable"
                or feedback.should_disable
                or outcome_policy.get("severe_regression")
            ):
                return "reject_candidate", "", {"experiment_id": pending["id"]}
            return "keep", "", {"pending_experiment_id": pending["id"]}

        if (
            outcome_policy.get("rollback_candidate")
            and latest_rewrite
            and latest_rewrite.get("content_before")
        ):
            return (
                "rollback",
                self._build_rollback_content(
                    restored=latest_rewrite["content_before"],
                    section=packet.update_section,
                    reference_content=reference_content,
                ),
                {},
            )

        if (
            latest_rewrite
            and self.memory.resolve_skill_status(packet.skill_name) == OBSERVING_STATUS
        ):
            # Runtime rewrites take effect immediately. Judge only evidence
            # recorded after that rewrite before confirming or rolling back.
            outcome = observation_outcome(packet, latest_rewrite)
            meta = {"observation": outcome.window}
            if outcome.verdict == "confirm":
                return "confirm", "", meta
            if outcome.verdict == "rollback" and latest_rewrite.get("content_before"):
                return (
                    "rollback",
                    self._build_rollback_content(
                        restored=latest_rewrite["content_before"],
                        section=packet.update_section,
                        reference_content=reference_content,
                    ),
                    meta,
                )
            return "keep", "", meta

        if execution_decision == "disable" or (
            feedback.should_disable
            and not (packet.execution_evaluations and feedback.signal_samples == 0)
        ):
            if latest_rewrite and latest_rewrite.get("content_before"):
                return (
                    "rollback",
                    self._build_rollback_content(
                        restored=latest_rewrite["content_before"],
                        section=packet.update_section,
                        reference_content=reference_content,
                    ),
                    {},
                )
            return "disable", "", {}

        if outcome_policy.get("severe_regression") and not latest_rewrite:
            return "disable", "", {}

        if outcome_policy.get("rewrite_candidate"):
            proposed, source = self._build_rewrite_content(
                current=packet.current_content,
                packet=packet,
                reference_content=reference_content,
            )
            if proposed:
                return "rewrite", proposed, {"rewrite_source": source}

        if packet.exemplar_slice and feedback.should_rewrite:
            proposed, source = self._build_rewrite_content(
                current=packet.current_content,
                packet=packet,
                reference_content=reference_content,
            )
            if proposed:
                return "rewrite", proposed, {"rewrite_source": source}

        if execution_decision == "rewrite":
            proposed, source = self._build_rewrite_content(
                current=packet.current_content,
                packet=packet,
                reference_content=reference_content,
            )
            if proposed:
                return "rewrite", proposed, {"rewrite_source": source}

        if packet.surface == "run" and reference_content.strip():
            refreshed = self._build_refresh_content(
                current=packet.current_content,
                section=packet.update_section,
                reference_content=reference_content,
            )
            if refreshed and refreshed != packet.current_content:
                return "refresh", refreshed, {}

        return "keep", "", {}

    def rewrite_is_due(self, packet: IterationDecisionPacket) -> bool:
        """Cheap pre-check for call sites that generate LLM rewrite proposals."""
        if self.memory.resolve_skill_status(packet.skill_name) == OBSERVING_STATUS:
            return False
        if packet.surface == "eval" and self.memory.list_skill_experiments(
            packet.skill_name, status="candidate", limit=1
        ):
            return False
        feedback = packet.feedback or summarise_skill_feedback(packet.executions)
        outcome_policy = (packet.outcome_summary or {}).get("policy_state", {})
        return bool(
            outcome_policy.get("rewrite_candidate")
            or (packet.exemplar_slice and feedback.should_rewrite)
            or self._execution_contract_decision(packet) in {"rewrite", "disable"}
        )

    def _apply_decision(
        self,
        *,
        packet: IterationDecisionPacket,
        decision: str,
        proposed_content: str,
        harness_task_id: str,
        proposal_meta: dict[str, Any] | None = None,
    ) -> tuple[UpdateResult, str]:
        evidence = {**self._lifecycle_evidence(packet), **(proposal_meta or {})}
        current_status = self.memory.resolve_skill_status(packet.skill_name)

        if decision in {"rewrite", "refresh"} and proposed_content:
            if packet.surface == "eval":
                return self._stage_candidate(
                    packet=packet,
                    proposed_content=proposed_content,
                    harness_task_id=harness_task_id,
                    evidence=evidence,
                    strategy=f"skill_{decision}_candidate",
                )
            return self._apply_runtime_update(
                packet=packet,
                decision=decision,
                proposed_content=proposed_content,
                harness_task_id=harness_task_id,
                evidence=evidence,
            )

        if decision == "confirm":
            reason = "Observation window confirmed the last rewrite"
            self.memory.upsert_skill_state(
                packet.skill_name,
                origin=packet.skill_origin,
                path=packet.skill_path,
                status="active",
                reason=reason,
                evidence=evidence,
            )
            self.memory.record_skill_lifecycle_event(
                packet.skill_name,
                "confirm",
                status="active",
                path=packet.skill_path,
                harness_task_id=harness_task_id,
                reason=reason,
                evidence=evidence,
                content_before=packet.current_content,
                content_after=packet.current_content,
            )
            return (
                UpdateResult(
                    path=packet.skill_path,
                    strategy="skill_confirm",
                    has_changes=False,
                    old_content=packet.current_content,
                    new_content=packet.current_content,
                ),
                "active",
            )

        if decision == "rollback" and proposed_content:
            _atomic_write_skill(
                Path(packet.skill_path),
                proposed_content,
                expected_name=packet.skill_name,
            )
            self.memory.upsert_skill_state(
                packet.skill_name,
                origin=packet.skill_origin,
                path=packet.skill_path,
                status="active",
                reason="Automatic observation rolled back the last Skill rewrite",
                evidence=evidence,
            )
            self.memory.record_skill_lifecycle_event(
                packet.skill_name,
                "rollback",
                status="active",
                path=packet.skill_path,
                harness_task_id=harness_task_id,
                reason="Automatic observation restored the previous active Skill",
                evidence=evidence,
                content_before=packet.current_content,
                content_after=proposed_content,
            )
            return (
                UpdateResult(
                    path=packet.skill_path,
                    strategy="skill_rollback",
                    has_changes=True,
                    old_content=packet.current_content,
                    new_content=proposed_content,
                ),
                "active",
            )

        if decision == "disable":
            self.memory.set_skill_state(
                packet.skill_name,
                "disabled",
                origin=packet.skill_origin,
                path=packet.skill_path,
                reason="Iteration harness disabled the skill after negative evidence",
                evidence=evidence,
            )
            self.memory.record_skill_lifecycle_event(
                packet.skill_name,
                "disable",
                status="disabled",
                path=packet.skill_path,
                harness_task_id=harness_task_id,
                reason="Iteration harness disabled the skill",
                evidence=evidence,
                content_before=packet.current_content,
                content_after=packet.current_content,
            )
            return (
                UpdateResult(
                    path=packet.skill_path,
                    strategy="skill_disable",
                    has_changes=False,
                    old_content=packet.current_content,
                    new_content=packet.current_content,
                ),
                "disabled",
            )

        if decision == "reject_candidate":
            experiment_id = str(evidence.get("experiment_id") or "")
            self.memory.transition_skill_experiment(
                experiment_id,
                "rejected",
                reason="New negative evidence arrived before candidate validation",
                evidence={"harness_task_id": harness_task_id},
            )
            self.memory.record_skill_lifecycle_event(
                packet.skill_name,
                "reject",
                status="active",
                path=packet.skill_path,
                harness_task_id=harness_task_id,
                reason="Rejected pending candidate; active Skill remained unchanged",
                evidence=evidence,
                content_before=packet.current_content,
                content_after=packet.current_content,
            )
            return (
                UpdateResult(
                    path=f"candidate://{experiment_id}",
                    strategy="skill_candidate_rejected",
                    has_changes=False,
                    old_content=packet.current_content,
                    new_content=packet.current_content,
                ),
                current_status,
            )

        return (
            UpdateResult(
                path=packet.skill_path,
                strategy="skill_keep",
                has_changes=False,
                old_content=packet.current_content,
                new_content=packet.current_content,
            ),
            current_status,
        )

    def _apply_runtime_update(
        self,
        *,
        packet: IterationDecisionPacket,
        decision: str,
        proposed_content: str,
        harness_task_id: str,
        evidence: dict[str, Any],
    ) -> tuple[UpdateResult, str]:
        """Replace the active runtime Skill immediately and keep rollback evidence."""
        updated_content = proposed_content
        status = OBSERVING_STATUS if decision == "rewrite" else "active"
        if split_frontmatter(updated_content)[0]:
            updated_content = _set_frontmatter_version(
                updated_content,
                _next_runtime_version(packet.skill_version),
            )
        source_execution_ids = self._source_execution_ids(packet)
        update_evidence = {
            **evidence,
            "source_execution_ids": source_execution_ids,
            "previous_digest": text_digest(packet.current_content),
            "updated_digest": text_digest(updated_content),
        }
        _atomic_write_skill(
            Path(packet.skill_path),
            updated_content,
            expected_name=packet.skill_name,
        )
        reason = (
            "Automatic Skill rewrite applied; observing post-rewrite evidence"
            if decision == "rewrite"
            else "Automatic Skill reference refresh applied"
        )
        self.memory.upsert_skill_state(
            packet.skill_name,
            origin=packet.skill_origin,
            path=packet.skill_path,
            status=status,
            reason=reason,
            evidence=update_evidence,
        )
        self.memory.record_skill_lifecycle_event(
            packet.skill_name,
            decision,
            status=status,
            path=packet.skill_path,
            harness_task_id=harness_task_id,
            reason=reason,
            evidence=update_evidence,
            content_before=packet.current_content,
            content_after=updated_content,
        )
        return (
            UpdateResult(
                path=packet.skill_path,
                strategy=f"skill_{decision}",
                has_changes=True,
                old_content=packet.current_content,
                new_content=updated_content,
            ),
            status,
        )

    def _source_execution_ids(self, packet: IterationDecisionPacket) -> list[int]:
        evidence_execution_ids = {
            int(item["execution_id"])
            for item in packet.execution_evaluations + packet.typed_evaluation_results
            if item.get("execution_id")
        }
        if not evidence_execution_ids:
            evidence_execution_ids = {
                int(item["id"]) for item in packet.executions if item.get("id")
            }
        relevant_versions = {packet.skill_version, ""}
        relevant_versions.update(
            str(experiment.get("candidate_version") or "")
            for experiment in packet.experiment_history
            if experiment.get("status") == "rejected"
        )
        source_execution_ids = []
        for execution_id in sorted(evidence_execution_ids):
            execution = self.memory.get_skill_executions_by_id(execution_id)
            if execution is None or execution["skill_name"] != packet.skill_name:
                continue
            if str(execution.get("skill_version") or "") not in relevant_versions:
                continue
            source_execution_ids.append(execution_id)
        return source_execution_ids

    def _stage_candidate(
        self,
        *,
        packet: IterationDecisionPacket,
        proposed_content: str,
        harness_task_id: str,
        evidence: dict[str, Any],
        strategy: str,
    ) -> tuple[UpdateResult, str]:
        """Persist a candidate without modifying the active Skill file."""
        source_execution_ids = self._source_execution_ids(packet)
        timestamp = datetime.now(timezone.utc).strftime("%Y%m%d%H%M%S%f")
        parent_version = packet.skill_version or "unversioned"
        candidate_version = f"{parent_version}-candidate-{timestamp}"
        proposed_content = _set_frontmatter_version(proposed_content, candidate_version)
        experiment_id = self.memory.create_skill_experiment(
            skill_name=packet.skill_name,
            parent_version=parent_version,
            parent_digest=text_digest(packet.current_content),
            parent_content=packet.current_content,
            candidate_version=candidate_version,
            candidate_digest=text_digest(proposed_content),
            candidate_content=proposed_content,
            source_execution_ids=source_execution_ids,
            model_ref={"proposal_source": evidence.get("rewrite_source", "template")},
            policy={"requires_validation": True, "allow_non_holdout_promotion": False},
        )
        candidate_evidence = {
            **evidence,
            "experiment_id": experiment_id,
            "source_execution_ids": source_execution_ids,
            "candidate_digest": text_digest(proposed_content),
        }
        self.memory.upsert_skill_state(
            packet.skill_name,
            origin=packet.skill_origin,
            path=packet.skill_path,
            status="active",
            reason="Candidate staged; active Skill unchanged pending validation",
            evidence=candidate_evidence,
        )
        self.memory.record_skill_lifecycle_event(
            packet.skill_name,
            "candidate",
            status="candidate",
            path=packet.skill_path,
            harness_task_id=harness_task_id,
            reason="Candidate staged for execution-grounded validation",
            evidence=candidate_evidence,
            content_before=packet.current_content,
            content_after=proposed_content,
        )
        return (
            UpdateResult(
                path=f"candidate://{experiment_id}",
                strategy=strategy,
                has_changes=False,
                old_content=packet.current_content,
                new_content=proposed_content,
            ),
            "candidate",
        )

    @staticmethod
    def _latest_rewrite_event(history: list[dict[str, Any]]) -> dict[str, Any] | None:
        for event in history:
            if event.get("action") == "rollback":
                return None
            if event.get("action") == "rewrite":
                return event
        return None

    def _post_rewrite_evaluations(self, packet: IterationDecisionPacket) -> list[dict[str, Any]]:
        """Only evaluations recorded strictly after the latest rewrite are decision evidence.

        Without this cutoff, stale pre-rewrite scores re-trigger a rewrite
        right after an observation window confirms one.
        """
        latest = self._latest_rewrite_event(packet.lifecycle_history)
        if not latest:
            return packet.execution_evaluations
        cutoff = str(latest.get("created_at") or "")
        return [
            item
            for item in packet.execution_evaluations
            if str(item.get("created_at") or "") > cutoff
        ]

    @staticmethod
    def _execution_contract_evidence_summary(evaluations: list[dict[str, Any]]) -> dict[str, Any]:
        scores = [
            float(item["aggregate_score"])
            for item in evaluations
            if item.get("aggregate_score") is not None
        ]
        criteria_totals: dict[str, list[float]] = {}
        for item in evaluations:
            for name, score in (item.get("criteria_scores") or {}).items():
                try:
                    criteria_totals.setdefault(name, []).append(float(score))
                except (TypeError, ValueError):
                    continue
        criteria_averages = {
            name: sum(values) / len(values) for name, values in criteria_totals.items() if values
        }
        lowest = sorted(criteria_averages, key=criteria_averages.get)[:3]
        return {
            "samples": len(scores),
            "average_score": (sum(scores) / len(scores)) if scores else None,
            "criteria_averages": criteria_averages,
            "lowest_criteria": lowest,
        }

    def _execution_contract_decision(self, packet: IterationDecisionPacket) -> str:
        typed_decision = self._typed_execution_decision(packet)
        if typed_decision != "keep":
            return typed_decision
        contract = packet.execution_contract or {}
        summary = self._execution_contract_evidence_summary(self._post_rewrite_evaluations(packet))
        average = summary["average_score"]
        samples = summary["samples"]
        if average is None or samples <= 0:
            return "keep"

        disable_below = float(contract.get("disable_below_score", 0.25) or 0.25)
        rewrite_below = float(contract.get("rewrite_below_score", 0.55) or 0.55)
        min_disable = int(contract.get("min_samples_for_disable", 2) or 2)
        min_rewrite = int(contract.get("min_samples_for_rewrite", 3) or 3)

        if samples >= min_disable and average <= disable_below:
            return "disable"
        if samples >= min_rewrite and average <= rewrite_below:
            return "rewrite"
        return "keep"

    @staticmethod
    def _typed_execution_decision(packet: IterationDecisionPacket) -> str:
        aggregate = packet.governance_aggregate or {}
        direct_hard_gates = [
            failure
            for failure in aggregate.get("hard_gate_failures", [])
            if failure.get("attribution_grade") in {"direct", "controlled"}
        ]
        if direct_hard_gates:
            return "disable"
        repeated = aggregate.get("actionable_failure_modes") or {}
        if any(int(count) >= 3 for count in repeated.values()):
            return "rewrite"
        rejected_versions = {
            str(experiment.get("candidate_version") or "")
            for experiment in packet.experiment_history
            if experiment.get("status") in {"rejected", "inconclusive"}
        }
        rejected_failures: dict[str, int] = {}
        for result in packet.typed_evaluation_results:
            if result.get("skill_version") not in rejected_versions:
                continue
            if result.get("verdict") != "fail" or result.get("attribution_grade") not in {
                "direct",
                "controlled",
            }:
                continue
            for failure in result.get("failure_modes") or []:
                name = str(failure)
                rejected_failures[name] = rejected_failures.get(name, 0) + 1
        if any(count >= 3 for count in rejected_failures.values()):
            return "rewrite"
        return "keep"

    @staticmethod
    def _summarise(text: str, limit: int = 160) -> str:
        compact = " ".join((text or "").split())
        if len(compact) <= limit:
            return compact
        return compact[: limit - 1] + "…"

    def _build_rewrite_content(
        self,
        *,
        current: str,
        packet: IterationDecisionPacket,
        reference_content: str,
    ) -> tuple[str, str]:
        """Return (proposed content, source) where source is "llm" or "template"."""
        llm_candidate = self._llm_rewrite_candidate(packet, reference_content)
        if llm_candidate:
            return llm_candidate, "llm"
        prefix, body = split_frontmatter(current)
        instructions_body = extract_section(body, "## Instructions")
        if instructions_body is None:
            return "", "template"
        rewritten = _build_rewritten_instructions(
            instructions_body,
            outcome_contract=packet.outcome_contract or {},
            outcome_summary=packet.outcome_summary,
            regression_summary=packet.regression_summary,
            exemplar_slice=packet.exemplar_slice,
            feedback=packet.feedback or summarise_skill_feedback(packet.executions),
            governance_aggregate=packet.governance_aggregate,
        )
        new_body = replace_section(body, "## Instructions", rewritten)
        if reference_content.strip():
            new_body = replace_section(new_body, packet.update_section, reference_content)
        content = (prefix + new_body.rstrip() + "\n") if prefix else (new_body.rstrip() + "\n")
        return content, "template"

    def _llm_rewrite_candidate(
        self,
        packet: IterationDecisionPacket,
        reference_content: str,
    ) -> str:
        """Prefer a caller-supplied LLM rewrite only when it passes the review gate."""
        proposal = (packet.llm_rewrite_proposal or "").rstrip()
        if not proposal:
            return ""
        candidate = proposal + "\n"
        if reference_content.strip():
            prefix, body = split_frontmatter(candidate)
            body = replace_section(body, packet.update_section, reference_content)
            candidate = (prefix + body.rstrip() + "\n") if prefix else (body.rstrip() + "\n")
        if not review_proposal("rewrite", packet, candidate).approved:
            return ""
        return candidate

    def _build_rollback_content(
        self,
        *,
        restored: str,
        section: str,
        reference_content: str,
    ) -> str:
        if not reference_content.strip():
            return restored
        prefix, body = split_frontmatter(restored)
        updated_body = replace_section(body, section, reference_content)
        return (prefix + updated_body.rstrip() + "\n") if prefix else (updated_body.rstrip() + "\n")

    def _build_refresh_content(
        self,
        *,
        current: str,
        section: str,
        reference_content: str,
    ) -> str:
        prefix, body = split_frontmatter(current)
        updated_body = replace_section(body, section, reference_content)
        return (prefix + updated_body.rstrip() + "\n") if prefix else (updated_body.rstrip() + "\n")

    def _build_reference_content(self, packet: IterationDecisionPacket) -> str:
        legacy_patterns = packet.regression_summary.get("legacy_patterns", [])
        if (
            not packet.outcome_summary
            and not packet.execution_evaluations
            and not packet.governance_aggregate.get("contributing_execution_ids")
            and not packet.exemplar_slice
            and not legacy_patterns
        ):
            return ""
        lines = [packet.update_section, ""]
        timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        lines.append(f"*Auto-updated by evidune on {timestamp}*")
        lines.append("")

        primary_kpi = (packet.outcome_contract or {}).get("primary_kpi")
        if packet.outcome_summary and primary_kpi:
            lines.append(f"### KPI Window: {primary_kpi}")
            lines.append(f"- Sample size: {packet.outcome_summary.get('sample_count', 0)}")
            current_value = packet.outcome_summary.get("current_value")
            baseline_value = packet.outcome_summary.get("baseline_value")
            delta = packet.outcome_summary.get("delta")
            if current_value is not None:
                lines.append(f"- Current value: {current_value:.3f}")
            if baseline_value is not None:
                lines.append(f"- Baseline value: {baseline_value:.3f}")
            if delta is not None:
                lines.append(f"- Delta: {delta:.3f}")
            lines.append(f"- Confidence: {packet.outcome_summary.get('confidence', 0.0):.2f}")
            active = [
                key
                for key, value in (packet.outcome_summary.get("policy_state") or {}).items()
                if value is True
            ]
            lines.append(f"- Policy state: {', '.join(active) if active else 'stable'}")
            lines.append("")

        segments = (packet.outcome_summary or {}).get("segment_breakdown") or []
        if segments:
            lines.append("### Segment Breakdown")
            for segment in segments:
                label = ", ".join(f"{k}={v}" for k, v in segment.get("segment", {}).items())
                lines.append(
                    f"- {label or '(unlabeled)'}: value={segment['value']:.3f}, "
                    f"samples={segment['sample_count']}"
                )
            lines.append("")

        if packet.exemplar_slice:
            lines.append("### Exemplars")
            for exemplar in packet.exemplar_slice:
                label = exemplar.get("exemplar") or exemplar.get("entity_id") or "example"
                value = exemplar.get(primary_kpi, None) if primary_kpi else None
                if value is None:
                    lines.append(f"- {label}")
                else:
                    lines.append(f"- {label} ({primary_kpi}={value:.3f})")
            lines.append("")

        if legacy_patterns:
            lines.append("### Observed Patterns")
            for pattern in legacy_patterns[:3]:
                lines.append(f"- {pattern}")
            lines.append("")

        if packet.execution_evaluations:
            summary = self._execution_contract_evidence_summary(packet.execution_evaluations)
            lines.append("### Execution Contract Evidence")
            lines.append(f"- Samples: {summary['samples']}")
            if summary["average_score"] is not None:
                lines.append(f"- Average score: {summary['average_score']:.2f}")
            if summary["lowest_criteria"]:
                lines.append(f"- Lowest criteria: {', '.join(summary['lowest_criteria'])}")
            lines.append("")

        if packet.governance_aggregate.get("contributing_execution_ids"):
            lines.append("### Typed Execution Evidence")
            lines.append(
                "- Contributing executions: "
                + ", ".join(
                    str(value)
                    for value in packet.governance_aggregate["contributing_execution_ids"]
                )
            )
            for failure, count in packet.governance_aggregate.get(
                "actionable_failure_modes", {}
            ).items():
                lines.append(f"- Failure `{failure}`: {count} attributed execution(s)")
            lines.append("")

        return "\n".join(lines)

    def _evidence_payload(self, packet: IterationDecisionPacket) -> dict[str, Any]:
        feedback = packet.feedback or summarise_skill_feedback(packet.executions)
        return {
            "origin": packet.skill_origin,
            "execution_summary": self._execution_contract_evidence_summary(
                packet.execution_evaluations
            ),
            "typed_execution_summary": packet.governance_aggregate,
            "outcome_summary": packet.outcome_summary or {},
            "feedback_summary": feedback.evidence,
            "lifecycle_context": {
                "lifecycle_events": len(packet.lifecycle_history),
                "recent_actions": [event["action"] for event in packet.lifecycle_history[:5]],
            },
            "exemplar_count": len(packet.exemplar_slice),
        }

    def _lifecycle_evidence(self, packet: IterationDecisionPacket) -> dict[str, Any]:
        return self._evidence_payload(packet)
